#Accelerometers
accelerometer_noise_density: 1.356e-03   #Noise density (continuous-time)
accelerometer_random_walk:   2.2e-05   #Bias random walk

#Gyroscopes
gyroscope_noise_density: 2.09e-04   #Noise density (continuous-time)
gyroscope_random_walk:   2.0e-06   #Bias random walk

rostopic: /xsens_driver/imu/data     #the IMU ROS topic
update_rate:            200.0      #Hz (for discretization of the values above)